#!/usr/bin/env bash

set -eol pipefail

# USAGE:
#   v2gif input.mp4 720 output.gif
#         ^ input   ^    ^ output file
#                   |
#                   size
#

ffmpeg \
  -i "$1" \
  -filter_complex "[0:v] fps=12,scale=${2}:-1,split [a][b];[a] palettegen [p];[b][p] paletteuse"
  "${3}
