cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap "homebrew/cask"

brew 'colordiff'
brew 'coreutils'
brew 'ffmpeg'
brew 'gettext'
brew 'gpg2'
brew 'go'
brew 'grc'
brew 'htop'
brew 'imagemagick'
brew 'jq'
brew 'openssl'
brew 'pinentry-mac'
brew 'node'
brew 'readline'
brew 'ruby-build'
brew 'siege'
brew 'tree'
brew 'watch'
brew 'wget'

mas '1password', id: 1333542190
cask 'chruby'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'ngrok'
cask 'disk-inventory-x'
cask 'kitty'
cask 'slack'
cask 'rectangle'
cask 'spotify'
cask 'sublime-text'
cask 'vlc'
