#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh -exec bash {} \;

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle check || brew bundle || true
